services:
  app:
    build:
      context: /project/bookmyfest/.devcontainer
      dockerfile: ./DockerFile
    volumes:
      - ../:/workspace
    command: sleep infinity
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres
volumes:
  postgres-data:

